# Generated by Django 2.0.10 on 2019-05-02 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
