sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
  - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
  - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
  - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
language: python
python:
  - "3.6"

addons:
  postgresql: "9.6"

env:
  - DATABASE_URL="postgres://postgres:fridgenotice@127.0.0.1:5432/fridgenotice"
  - USE_DOCKER=no

install:
  - pip install -r requirements/local.txt

before_script:
  - createdb --encoding=UTF-8 fridgenotice --username=postgres --owner=`whoami`

script:
  - coverage run manage.py test
  - coverage report -m --fail-under 80
  - flake8 .
