# Generated by Django 2.0.10 on 2019-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0002_auto_20190426_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='detail',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
