# Generated by Django 2.0.10 on 2019-04-30 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0003_auto_20190430_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date_filed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
