# Generated by Django 2.0.10 on 2019-04-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0005_auto_20190430_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='date_fieled',
            new_name='date_field',
        ),
    ]
