# Generated by Django 2.0.10 on 2019-05-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0006_auto_20190430_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
