# Generated by Django 2.0.10 on 2019-05-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(db_column='ingredient_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
